sonar.projectKey=reisack_GOFScoreboardAndroid
sonar.organization=reisack
sonar.host.url=https://sonarcloud.io
sonar.projectName=GOFScoreboardAndroid

sonar.sources=app/src/main/java
sonar.tests=app/src/test/java,app/src/androidTest/java
sonar.sourceEncoding=UTF-8

sonar.java.binaries=app/build/tmp/kotlin-classes/debug,app/build/intermediates/javac/debug/classes
sonar.kotlin.binaries=app/build/tmp/kotlin-classes/debug
sonar.java.libraries=app/build/intermediates/compile_app_classes_jar/debug/bundleDebugClassesToCompileJar/classes.jar

sonar.coverage.jacoco.xmlReportPaths=app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml,app/build/reports/jacoco/jacocoTestDebugReport/jacocoTestDebugReport.xml
