sonar.projectKey=reisack_GOFScoreboardAndroid
sonar.organization=reisack
sonar.host.url=https://sonarcloud.io
sonar.projectName=GOFScoreboardAndroid

sonar.sources=src/main/java
sonar.tests=src/test/java,src/androidTest/java
sonar.sourceEncoding=UTF-8

sonar.java.binaries=build/tmp/kotlin-classes/debug,build/intermediates/javac/debug/classes
sonar.kotlin.binaries=build/tmp/kotlin-classes/debug
sonar.java.libraries=build/intermediates/compile_app_classes_jar/debug/bundleDebugClassesToCompileJar/classes.jar

sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml,build/reports/jacoco/jacocoTestDebugReport/jacocoTestDebugReport.xml
